In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\pavan\OneDrive\Desktop\STUDENT_PERFORAMNCE_DASHBOARD\DATA\Student_performance_10k.csv")
df

,roll_no,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,science_score,total_score,grade
0,std-01,male,group D,some college,1.0,1.0,89,38.0,85.0,26.0,238.0,C
1,std-02,male,group B,high school,1.0,0.0,65,100.0,67.0,96.0,328.0,A
2,std-03,male,group C,master's degree,1.0,0.0,10,99.0,97.0,58.0,264.0,B
3,std-04,male,group D,some college,1.0,1.0,22,51.0,41.0,84.0,198.0,D
4,std-05,male,group C,some college,0.0,1.0,26,58.0,64.0,65.0,213.0,C
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,std-9996,female,group C,some college,1.0,0.0,78,60.0,46.0,58.0,242.0,C
9996,std-9997,female,group C,bachelor's degree,1.0,0.0,37,92.0,99.0,73.0,301.0,B
9997,std-9998,female,group B,associate's degree,1.0,1.0,70,71.0,100.0,90.0,331.0,A
9998,std-9999,female,group B,some high school,1.0,0.0,87,60.0,100.0,89.0,336.0,A
9999,std-10000,female,group B,high school,1.0,0.0,31,89.0,93.0,80.0,293.0,B

In [3]:
df.head()

,roll_no,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,science_score,total_score,grade
0,std-01,male,group D,some college,1.0,1.0,89,38.0,85.0,26.0,238.0,C
1,std-02,male,group B,high school,1.0,0.0,65,100.0,67.0,96.0,328.0,A
2,std-03,male,group C,master's degree,1.0,0.0,10,99.0,97.0,58.0,264.0,B
3,std-04,male,group D,some college,1.0,1.0,22,51.0,41.0,84.0,198.0,D
4,std-05,male,group C,some college,0.0,1.0,26,58.0,64.0,65.0,213.0,C

In [4]:
df.tail()

,roll_no,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,science_score,total_score,grade
9995,std-9996,female,group C,some college,1.0,0.0,78,60.0,46.0,58.0,242.0,C
9996,std-9997,female,group C,bachelor's degree,1.0,0.0,37,92.0,99.0,73.0,301.0,B
9997,std-9998,female,group B,associate's degree,1.0,1.0,70,71.0,100.0,90.0,331.0,A
9998,std-9999,female,group B,some high school,1.0,0.0,87,60.0,100.0,89.0,336.0,A
9999,std-10000,female,group B,high school,1.0,0.0,31,89.0,93.0,80.0,293.0,B

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   roll_no                      9999 non-null   str
 1   gender                       9982 non-null   str
 2   race_ethnicity               9977 non-null   str
 3   parental_level_of_education  9978 non-null   str
 4   lunch                        9976 non-null   float64
 5   test_preparation_course      9977 non-null   float64
 6   math_score                   9976 non-null   str
 7   reading_score                9975 non-null   float64
 8   writing_score                9976 non-null   float64
 9   science_score                9977 non-null   float64
 10  total_score                  9981 non-null   float64
 11  grade                        9997 non-null   str
dtypes: float64(6), str(6)
memory usage: 1.3 MB

In [6]:
df.describe()

,lunch,test_preparation_course,reading_score,writing_score,science_score,total_score
count,9976.000000,9977.000000,9975.000000,9976.000000,9977.000000,9981.000000
mean,0.644246,0.388694,70.125915,71.415798,66.063045,264.740908
std,0.478765,0.487478,19.026245,18.245360,19.324331,42.304858
min,0.000000,0.000000,17.000000,10.000000,9.000000,89.000000
25%,0.000000,0.000000,57.000000,59.000000,53.000000,237.000000
50%,1.000000,0.000000,71.000000,72.500000,67.000000,268.000000
75%,1.000000,1.000000,85.000000,85.000000,81.000000,294.000000
max,1.000000,1.000000,100.000000,100.000000,100.000000,383.000000

In [7]:
df.isnull().sum()

roll_no                         1
gender                         18
race_ethnicity                 23
parental_level_of_education    22
lunch                          24
test_preparation_course        23
math_score                     24
reading_score                  25
writing_score                  24
science_score                  23
total_score                    19
grade                           3
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
#removing the duplicates from my data sets 
df = df.drop_duplicates()
df

,roll_no,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,science_score,total_score,grade
0,std-01,male,group D,some college,1.0,1.0,89,38.0,85.0,26.0,238.0,C
1,std-02,male,group B,high school,1.0,0.0,65,100.0,67.0,96.0,328.0,A
2,std-03,male,group C,master's degree,1.0,0.0,10,99.0,97.0,58.0,264.0,B
3,std-04,male,group D,some college,1.0,1.0,22,51.0,41.0,84.0,198.0,D
4,std-05,male,group C,some college,0.0,1.0,26,58.0,64.0,65.0,213.0,C
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,std-9996,female,group C,some college,1.0,0.0,78,60.0,46.0,58.0,242.0,C
9996,std-9997,female,group C,bachelor's degree,1.0,0.0,37,92.0,99.0,73.0,301.0,B
9997,std-9998,female,group B,associate's degree,1.0,1.0,70,71.0,100.0,90.0,331.0,A
9998,std-9999,female,group B,some high school,1.0,0.0,87,60.0,100.0,89.0,336.0,A
9999,std-10000,female,group B,high school,1.0,0.0,31,89.0,93.0,80.0,293.0,B

In [10]:
df.dtypes

roll_no                            str
gender                             str
race_ethnicity                     str
parental_level_of_education        str
lunch                          float64
test_preparation_course        float64
math_score                         str
reading_score                  float64
writing_score                  float64
science_score                  float64
total_score                    float64
grade                              str
dtype: object

In [11]:
#converting math_score column into numeric form
df["math_score"] = pd.to_numeric(df["math_score"],errors = "coerce")
df["math_score"]

0       89.0
1       65.0
2       10.0
3       22.0
4       26.0
        ...
9995    78.0
9996    37.0
9997    70.0
9998    87.0
9999    31.0
Name: math_score, Length: 10000, dtype: float64

In [12]:
df.dtypes

roll_no                            str
gender                             str
race_ethnicity                     str
parental_level_of_education        str
lunch                          float64
test_preparation_course        float64
math_score                     float64
reading_score                  float64
writing_score                  float64
science_score                  float64
total_score                    float64
grade                              str
dtype: object

In [13]:
#these are the categorical columns 
categorical_columns = ["gender","race_ethnicity","parental_level_of_education","grade"]
df[categorical_columns] = df[categorical_columns].astype("category")
df[categorical_columns]

      gender race_ethnicity parental_level_of_education grade
0       male        group D                some college     C
1       male        group B                 high school     A
2       male        group C             master's degree     B
3       male        group D                some college     D
4       male        group C                some college     C
...      ...            ...                         ...   ...
9995  female        group C                some college     C
9996  female        group C           bachelor's degree     B
9997  female        group B          associate's degree     A
9998  female        group B            some high school     A
9999  female        group B                 high school     B

[10000 rows x 4 columns]

In [14]:
#checking the datatypes
df.dtypes

roll_no                             str
gender                         category
race_ethnicity                 category
parental_level_of_education    category
lunch                           float64
test_preparation_course         float64
math_score                      float64
reading_score                   float64
writing_score                   float64
science_score                   float64
total_score                     float64
grade                          category
dtype: object

In [15]:
df["lunch"].value_counts()

lunch
1.0    6427
0.0    3549
Name: count, dtype: int64

In [16]:
#checking how many total null values are there in each columns
df.isnull().sum()

roll_no                         1
gender                         18
race_ethnicity                 23
parental_level_of_education    22
lunch                          24
test_preparation_course        23
math_score                     25
reading_score                  25
writing_score                  24
science_score                  23
total_score                    19
grade                           3
dtype: int64

In [17]:
#handling missing value with numerical values
#handling the numerical value 
numeric_columns = ["math_score","reading_score","writing_score","science_score","total_score"]
for col in numeric_columns:
    df[col]=df[col].fillna(df[col].median())

In [18]:
df.isnull().sum()

roll_no                         1
gender                         18
race_ethnicity                 23
parental_level_of_education    22
lunch                          24
test_preparation_course        23
math_score                      0
reading_score                   0
writing_score                   0
science_score                   0
total_score                     0
grade                           3
dtype: int64

In [19]:
categorical_columns =["gender","race_ethnicity","parental_level_of_education","test_preparation_course"]
for col in categorical_columns:
    df[col] = df[col].fillna(df[col].mode()[0])

In [20]:
df.isnull().sum()

roll_no                         1
gender                          0
race_ethnicity                  0
parental_level_of_education     0
lunch                          24
test_preparation_course         0
math_score                      0
reading_score                   0
writing_score                   0
science_score                   0
total_score                     0
grade                           3
dtype: int64

In [21]:
df["lunch"] = df["lunch"].fillna(df["lunch"].mode()[0])

In [22]:
df = df.dropna(subset = ["grade"])

In [23]:
df.isnull().sum()

roll_no                        1
gender                         0
race_ethnicity                 0
parental_level_of_education    0
lunch                          0
test_preparation_course        0
math_score                     0
reading_score                  0
writing_score                  0
science_score                  0
total_score                    0
grade                          0
dtype: int64

In [24]:
df = df.drop(columns = ["roll_no"])

In [25]:
df.isnull().sum()

gender                         0
race_ethnicity                 0
parental_level_of_education    0
lunch                          0
test_preparation_course        0
math_score                     0
reading_score                  0
writing_score                  0
science_score                  0
total_score                    0
grade                          0
dtype: int64

In [26]:
df["grade"].value_counts()

grade
B       5659
C       2701
A        904
D        671
Fail      62
Name: count, dtype: int64

In [27]:
df["result"] = df["grade"].isin(["A","B","C"]).map({True:"pass" , False:"Fail"})

In [28]:
df["result"].value_counts()

result
pass    9264
Fail     733
Name: count, dtype: int64

In [29]:
df[["grade","result","total_score"]].head(10)

  grade result  total_score
0     C   pass        238.0
1     A   pass        328.0
2     B   pass        264.0
3     D   Fail        198.0
4     C   pass        213.0
5     C   pass        206.0
6     C   pass        239.0
7     D   Fail        156.0
8     B   pass        283.0
9     C   pass        217.0

In [30]:
# seprating the grade from the x features so that it will not get copied by result 
#x = features
#y = targets
x = df.drop(columns = ["grade","result"])
y = df["result"]

x.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,science_score,total_score
0,male,group D,some college,1.0,1.0,89.0,38.0,85.0,26.0,238.0
1,male,group B,high school,1.0,0.0,65.0,100.0,67.0,96.0,328.0
2,male,group C,master's degree,1.0,0.0,10.0,99.0,97.0,58.0,264.0
3,male,group D,some college,1.0,1.0,22.0,51.0,41.0,84.0,198.0
4,male,group C,some college,0.0,1.0,26.0,58.0,64.0,65.0,213.0

In [31]:
x = pd.get_dummies(x,drop_first= True)
x.head()

,lunch,test_preparation_course,math_score,reading_score,writing_score,science_score,total_score,gender_Girl,gender_\tmale,gender_female,...,race_ethnicity_group B,race_ethnicity_group C,race_ethnicity_group C\n,race_ethnicity_group D,race_ethnicity_group E,parental_level_of_education_bachelor's degree,parental_level_of_education_high school,parental_level_of_education_master's degree,parental_level_of_education_some college,parental_level_of_education_some high school
0,1.0,1.0,89.0,38.0,85.0,26.0,238.0,False,False,False,...,False,False,False,True,False,False,False,False,True,False
1,1.0,0.0,65.0,100.0,67.0,96.0,328.0,False,False,False,...,True,False,False,False,False,False,True,False,False,False
2,1.0,0.0,10.0,99.0,97.0,58.0,264.0,False,False,False,...,False,True,False,False,False,False,False,True,False,False
3,1.0,1.0,22.0,51.0,41.0,84.0,198.0,False,False,False,...,False,False,False,True,False,False,False,False,True,False
4,0.0,1.0,26.0,58.0,64.0,65.0,213.0,False,False,False,...,False,True,False,False,False,False,False,False,True,False

In [32]:
print(x.shape)
print(y.value_counts())

(9997, 26)
result
pass    9264
Fail     733
Name: count, dtype: int64

In [33]:
x.head()

,lunch,test_preparation_course,math_score,reading_score,writing_score,science_score,total_score,gender_Girl,gender_\tmale,gender_female,...,race_ethnicity_group B,race_ethnicity_group C,race_ethnicity_group C\n,race_ethnicity_group D,race_ethnicity_group E,parental_level_of_education_bachelor's degree,parental_level_of_education_high school,parental_level_of_education_master's degree,parental_level_of_education_some college,parental_level_of_education_some high school
0,1.0,1.0,89.0,38.0,85.0,26.0,238.0,False,False,False,...,False,False,False,True,False,False,False,False,True,False
1,1.0,0.0,65.0,100.0,67.0,96.0,328.0,False,False,False,...,True,False,False,False,False,False,True,False,False,False
2,1.0,0.0,10.0,99.0,97.0,58.0,264.0,False,False,False,...,False,True,False,False,False,False,False,True,False,False
3,1.0,1.0,22.0,51.0,41.0,84.0,198.0,False,False,False,...,False,False,False,True,False,False,False,False,True,False
4,0.0,1.0,26.0,58.0,64.0,65.0,213.0,False,False,False,...,False,True,False,False,False,False,False,False,True,False

In [34]:
# clean messy text in categorical columns before encoding
text_cols = ["gender", "race_ethnicity", "parental_level_of_education"]
for col in text_cols:
    df[col] = (
        df[col]
        .astype(str)
        .str.replace("\t", " ", regex=False)
        .str.replace("\n", " ", regex=False)
        .str.strip()
        .str.replace(r"\s+", " ", regex=True)
    )

df["gender"] = df["gender"].str.lower().replace({"girl": "female"})

print(df["gender"].value_counts())
print(df["race_ethnicity"].value_counts())
print(df["parental_level_of_education"].value_counts())

gender
female    5010
male      4980
boy          6
\tmale       1
Name: count, dtype: int64
race_ethnicity
group C      2943
group D      2565
group B      1899
group E      1508
group A      1062
D               6
group C\n       4
E               4
C               3
A               2
B               1
Name: count, dtype: int64
parental_level_of_education
some college          2294
high school           1986
associate's degree    1905
some high school      1741
bachelor's degree     1360
master's degree        711
Name: count, dtype: int64

In [35]:
# rebuild features after cleaning; do not use grade, result, or total_score
x = df.drop(columns=["grade", "result", "total_score"])
y = df["result"]

x = pd.get_dummies(x, drop_first=True)
print(x.shape)
print(x.columns.tolist())
x.head()

(9997, 24)
['lunch', 'test_preparation_course', 'math_score', 'reading_score', 'writing_score', 'science_score', 'gender_boy', 'gender_female', 'gender_male', 'race_ethnicity_B', 'race_ethnicity_C', 'race_ethnicity_D', 'race_ethnicity_E', 'race_ethnicity_group A', 'race_ethnicity_group B', 'race_ethnicity_group C', 'race_ethnicity_group C\\n', 'race_ethnicity_group D', 'race_ethnicity_group E', "parental_level_of_education_bachelor's degree", 'parental_level_of_education_high school', "parental_level_of_education_master's degree", 'parental_level_of_education_some college', 'parental_level_of_education_some high school']

,lunch,test_preparation_course,math_score,reading_score,writing_score,science_score,gender_boy,gender_female,gender_male,race_ethnicity_B,...,race_ethnicity_group B,race_ethnicity_group C,race_ethnicity_group C\n,race_ethnicity_group D,race_ethnicity_group E,parental_level_of_education_bachelor's degree,parental_level_of_education_high school,parental_level_of_education_master's degree,parental_level_of_education_some college,parental_level_of_education_some high school
0,1.0,1.0,89.0,38.0,85.0,26.0,False,False,True,False,...,False,False,False,True,False,False,False,False,True,False
1,1.0,0.0,65.0,100.0,67.0,96.0,False,False,True,False,...,True,False,False,False,False,False,True,False,False,False
2,1.0,0.0,10.0,99.0,97.0,58.0,False,False,True,False,...,False,True,False,False,False,False,False,True,False,False
3,1.0,1.0,22.0,51.0,41.0,84.0,False,False,True,False,...,False,False,False,True,False,False,False,False,True,False
4,0.0,1.0,26.0,58.0,64.0,65.0,False,False,True,False,...,False,True,False,False,False,False,False,False,True,False

In [36]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# use the cleaned dataframe, not the dummy-encoded x
X = df.drop(columns=["grade", "result", "total_score"])
y = df["result"]

numeric_features = [
    "lunch",
    "test_preparation_course",
    "math_score",
    "reading_score",
    "writing_score",
    "science_score",
]
categorical_features = ["gender", "race_ethnicity", "parental_level_of_education"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(X_train.shape, X_test.shape)
print(y_train.value_counts())

(7997, 9) (2000, 9)
result
pass    7411
Fail     586
Name: count, dtype: int64

In [37]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numeric_features),
        ("cat", OneHotEncoder(drop="first", handle_unknown="ignore"), categorical_features),
    ]
)

model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("classifier", LogisticRegression(max_iter=1000, class_weight="balanced")),
    ]
)

model

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['lunch',
                                                   'test_preparation_course',
                                                   'math_score',
                                                   'reading_score',
                                                   'writing_score',
                                                   'science_score']),
                                                 ('cat',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore'),
                                                  ['gender', 'race_ethnicity',
                                                   'parental_level_of_education'])])),
                ('classifier',
                 LogisticRegression(class_weight='balanced', max_iter=1000))])

In [38]:
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification report:\n", classification_report(y_test, y_pred))

Accuracy: 0.987

Confusion matrix:
 [[ 147    0]
 [  26 1827]]

Classification report:
               precision    recall  f1-score   support

        Fail       0.85      1.00      0.92       147
        pass       1.00      0.99      0.99      1853

    accuracy                           0.99      2000
   macro avg       0.92      0.99      0.96      2000
weighted avg       0.99      0.99      0.99      2000

In [39]:
import joblib
from pathlib import Path

Path("models").mkdir(exist_ok=True)
joblib.dump(model, "models/pass_fail_pipeline.joblib")
print("Saved:", Path("models/pass_fail_pipeline.joblib").resolve())

Saved: C:\Users\pavan\OneDrive\Desktop\STUDENT_PERFORAMNCE_DASHBOARD\models\pass_fail_pipeline.joblib

In [40]:
loaded_model = joblib.load("models/pass_fail_pipeline.joblib")

# one test row in the same column order as training X
sample = X_test.iloc[[0]]
print(sample)
print("True label:", y_test.iloc[0])
print("Prediction:", loaded_model.predict(sample)[0])
print("Probabilities:", loaded_model.predict_proba(sample))

     gender race_ethnicity parental_level_of_education  lunch  \
4746   male        group E            some high school    1.0

      test_preparation_course  math_score  reading_score  writing_score  \
4746                      0.0        84.0           97.0           64.0

      science_score
4746          100.0
True label: pass
Prediction: pass
Probabilities: [[0. 1.]]